source 'https://github.com/CocoaPods/Specs.git'
target 'MusicnMood' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Spartan'
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
